### ISSUE TITLE
GwMessageDecoderBenchmark fails

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#423]
```
/usr/lib/jvm/java-8-oracle/bin/java -javaagent:/home/artemvysochyn/Workspace/idea-IC-182.4892.20/lib/idea_rt.jar=34811:/home/artemvysochyn/Workspace/idea-IC-182.4892.20/bin -Dfile.encoding=UTF-8 -classpath /usr/lib/jvm/java-8-oracle/jre/lib/charsets.jar:/usr/lib/jvm/java-8-oracle/jre/lib/deploy.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/cldrdata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/dnsns.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jaccess.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/jfxrt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/localedata.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/nashorn.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunec.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunjce_provider.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/sunpkcs11.jar:/usr/lib/jvm/java-8-oracle/jre/lib/ext/zipfs.jar:/usr/lib/jvm/java-8-oracle/jre/lib/javaws.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jce.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfr.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jfxswt.jar:/usr/lib/jvm/java-8-oracle/jre/lib/jsse.jar:/usr/lib/jvm/java-8-oracle/jre/lib/management-agent.jar:/usr/lib/jvm/java-8-oracle/jre/lib/plugin.jar:/usr/lib/jvm/java-8-oracle/jre/lib/resources.jar:/usr/lib/jvm/java-8-oracle/jre/lib/rt.jar:/home/artemvysochyn/Workspace/scalecube-services/services-benchmarks/target/classes:/home/artemvysochyn/Workspace/scalecube-services/services/target/classes:/home/artemvysochyn/Workspace/scalecube-services/services-api/target/classes:/home/artemvysochyn/.m2/repository/io/netty/netty-buffer/4.1.29.Final/netty-buffer-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/io/projectreactor/reactor-core/3.2.1.RELEASE/reactor-core-3.2.1.RELEASE.jar:/home/artemvysochyn/.m2/repository/org/reactivestreams/reactive-streams/1.0.2/reactive-streams-1.0.2.jar:/home/artemvysochyn/.m2/repository/org/jctools/jctools-core/2.1.2/jctools-core-2.1.2.jar:/home/artemvysochyn/Workspace/scalecube-services/services-discovery/target/classes:/home/artemvysochyn/.m2/repository/io/scalecube/scalecube-cluster/2.1.4/scalecube-cluster-2.1.4.jar:/home/artemvysochyn/.m2/repository/io/scalecube/scalecube-transport/2.1.4/scalecube-transport-2.1.4.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-codec/4.1.29.Final/netty-codec-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-transport/4.1.29.Final/netty-transport-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-resolver/4.1.29.Final/netty-resolver-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.jar:/home/artemvysochyn/.m2/repository/com/fasterxml/jackson/core/jackson-core/2.9.6/jackson-core-2.9.6.jar:/home/artemvysochyn/.m2/repository/com/fasterxml/jackson/core/jackson-databind/2.9.6/jackson-databind-2.9.6.jar:/home/artemvysochyn/.m2/repository/com/fasterxml/jackson/core/jackson-annotations/2.9.0/jackson-annotations-2.9.0.jar:/home/artemvysochyn/.m2/repository/com/fasterxml/jackson/datatype/jackson-datatype-jsr310/2.9.6/jackson-datatype-jsr310-2.9.6.jar:/home/artemvysochyn/Workspace/scalecube-services/services-transport-rsocket/target/classes:/home/artemvysochyn/.m2/repository/org/slf4j/slf4j-api/1.7.7/slf4j-api-1.7.7.jar:/home/artemvysochyn/.m2/repository/io/rsocket/rsocket-core/0.11.8/rsocket-core-0.11.8.jar:/home/artemvysochyn/.m2/repository/io/rsocket/rsocket-transport-netty/0.11.8/rsocket-transport-netty-0.11.8.jar:/home/artemvysochyn/.m2/repository/io/projectreactor/netty/reactor-netty/0.8.1.RELEASE/reactor-netty-0.8.1.RELEASE.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-codec-http/4.1.29.Final/netty-codec-http-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-codec-http2/4.1.29.Final/netty-codec-http2-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-handler/4.1.29.Final/netty-handler-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-handler-proxy/4.1.29.Final/netty-handler-proxy-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-codec-socks/4.1.29.Final/netty-codec-socks-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-transport-native-epoll/4.1.29.Final/netty-transport-native-epoll-4.1.29.Final-linux-x86_64.jar:/home/artemvysochyn/.m2/repository/io/netty/netty-transport-native-unix-common/4.1.29.Final/netty-transport-native-unix-common-4.1.29.Final.jar:/home/artemvysochyn/Workspace/scalecube-services/services-transport-jackson/target/classes:/home/artemvysochyn/Workspace/scalecube-services/services-transport-protostuff/target/classes:/home/artemvysochyn/.m2/repository/io/netty/netty-common/4.1.29.Final/netty-common-4.1.29.Final.jar:/home/artemvysochyn/.m2/repository/io/protostuff/protostuff-core/1.6.0/protostuff-core-1.6.0.jar:/home/artemvysochyn/.m2/repository/io/protostuff/protostuff-api/1.6.0/protostuff-api-1.6.0.jar:/home/artemvysochyn/.m2/repository/io/protostuff/protostuff-collectionschema/1.6.0/protostuff-collectionschema-1.6.0.jar:/home/artemvysochyn/.m2/repository/io/protostuff/protostuff-runtime/1.6.0/protostuff-runtime-1.6.0.jar:/home/artemvysochyn/.m2/repository/io/scalecube/scalecube-benchmarks-api/1.2.2/scalecube-benchmarks-api-1.2.2.jar:/home/artemvysochyn/.m2/repository/io/scalecube/scalecube-benchmarks-log4j2/1.2.2/scalecube-benchmarks-log4j2-1.2.2.jar:/home/artemvysochyn/.m2/repository/org/apache/logging/log4j/log4j-slf4j-impl/2.11.0/log4j-slf4j-impl-2.11.0.jar:/home/artemvysochyn/.m2/repository/org/apache/logging/log4j/log4j-api/2.11.0/log4j-api-2.11.0.jar:/home/artemvysochyn/.m2/repository/org/apache/logging/log4j/log4j-core/2.11.0/log4j-core-2.11.0.jar:/home/artemvysochyn/.m2/repository/com/lmax/disruptor/3.4.2/disruptor-3.4.2.jar:/home/artemvysochyn/.m2/repository/io/dropwizard/metrics/metrics-core/3.1.2/metrics-core-3.1.2.jar:/home/artemvysochyn/Workspace/scalecube-services/services-gateway-http/target/classes:/home/artemvysochyn/Workspace/scalecube-services/services-gateway-common/target/classes:/home/artemvysochyn/Workspace/scalecube-services/services-gateway-websocket/target/classes:/home/artemvysochyn/Workspace/scalecube-services/services-gateway-rsocket/target/classes:/home/artemvysochyn/Workspace/scalecube-services/services-gateway-clientsdk/target/classes:/home/artemvysochyn/Workspace/scalecube-services/services-examples/target/classes:/home/artemvysochyn/.m2/repository/it/unimi/dsi/fastutil/8.1.1/fastutil-8.1.1.jar io.scalecube.services.benchmarks.gateway.codec.GwMessageDecoderBenchmark warmUpDurationInSec=1
I 2018-11-07T15:23:55,020 i.s.b.BenchmarkState Benchmarks settings: BenchmarkSettings{numberThreads=4, concurrency=16, minInterval=PT0.1S, executionTaskDuration=PT6M, executionTaskInterval=PT0S, numOfIterations=9223372036854775807, reporterInterval=PT3S, csvReporterDirectory=reports/benchmarks/i.s.s.b.g.c.GwMessageDecoderBenchmark/2018-11-07-13-23-53, taskName='i.s.s.b.g.c.GwMessageDecoderBenchmark', durationUnit=NANOSECONDS, rateUnit=SECONDS, warmUpDuration=PT1S, rampUpDuration=PT10S, rampUpInterval=PT1S, consoleReporterEnabled=true, injectors=0, messageRate=0, injectorsPerRampUpInterval=0, messagesPerExecutionInterval=0, options={}} [main]
I 2018-11-07T15:23:55,356 i.s.s.b.g.c.GwMessageCodecBenchmarkState generated ByteBuf: {"orderType":"Sell","side":"Sell","instanceId":"601ab5c5-53ff-4e42-a324-0f906ddbab15","quantity":9223372036854775807,"price":9223372036854775807,"isClosePositionOrder":false,"requestTimestamp":"2018-11-07T15:23:55.11","token":"eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJUZW5hbnQxIiwic3ViIjoiMSIsIm5hbWUiOiJ0cmFkZXIxIn0.j9dCs63J4xtWfhctrXb5popLAl8ohSlMTJU3_vCrQHk","sourceIpAddress":"255.255.255.255"} [main]
I 2018-11-07T15:23:55,359 i.s.s.b.g.c.GwMessageCodecBenchmarkState generated ByteBuf: {"q":"/some/service","sig":9,"sid":9223372036854775807,"d":{"orderType":"Sell","side":"Sell","instanceId":"d565c6cf-5e10-424c-a36a-5df6ff4d7d70","quantity":9223372036854775807,"price":9223372036854775807,"isClosePositionOrder":false,"requestTimestamp":"2018-11-07T15:23:55.358","token":"eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiJUZW5hbnQxIiwic3ViIjoiMSIsIm5hbWUiOiJ0cmFkZXIxIn0.j9dCs63J4xtWfhctrXb5popLAl8ohSlMTJU3_vCrQHk","sourceIpAddress":"255.255.255.255"}} [main]
#### i 2
#### i 3
MessageCodecException{errorMessage=Failed to decode message}
	at io.scalecube.services.gateway.ws.GatewayMessageCodec.decode(GatewayMessageCodec.java:159)
	at io.scalecube.services.benchmarks.gateway.codec.GwMessageDecoderBenchmark.lambda$null$0(GwMessageDecoderBenchmark.java:38)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: MessageCodecException{errorMessage=Root should be object}
	at io.scalecube.services.gateway.ws.GatewayMessageCodec.decode(GatewayMessageCodec.java:127)
	... 10 more
MessageCodecException{errorMessage=Failed to decode message}
	at io.scalecube.services.gateway.ws.GatewayMessageCodec.decode(GatewayMessageCodec.java:159)
	at io.scalecube.services.benchmarks.gateway.codec.GwMessageDecoderBenchmark.lambda$null$0(GwMessageDecoderBenchmark.java:38)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: MessageCodecException{errorMessage=Root should be object}
	at io.scalecube.services.gateway.ws.GatewayMessageCodec.decode(GatewayMessageCodec.java:127)
	... 10 more
#### i 4
MessageCodecException{errorMessage=Failed to decode message}
	at io.scalecube.services.gateway.ws.GatewayMessageCodec.decode(GatewayMessageCodec.java:159)
	at io.scalecube.services.benchmarks.gateway.codec.GwMessageDecoderBenchmark.lambda$null$0(GwMessageDecoderBenchmark.java:38)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: MessageCodecException{errorMessage=Root should be object}
	at io.scalecube.services.gateway.ws.GatewayMessageCodec.decode(GatewayMessageCodec.java:127)
	... 10 more
#### i 1
MessageCodecException{errorMessage=Failed to decode message}
	at io.scalecube.services.gateway.ws.GatewayMessageCodec.decode(GatewayMessageCodec.java:159)
	at io.scalecube.services.benchmarks.gateway.codec.GwMessageDecoderBenchmark.lambda$null$0(GwMessageDecoderBenchmark.java:38)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:100)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.runAsync(FluxPublishOn.java:398)
	at reactor.core.publisher.FluxPublishOn$PublishOnSubscriber.run(FluxPublishOn.java:484)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: MessageCodecException{errorMessage=Root should be object}
	at io.scalecube.services.gateway.ws.GatewayMessageCodec.decode(GatewayMessageCodec.java:127)
	... 10 more
11/7/18 3:23:55 PM =============================================================

-- Meters ----------------------------------------------------------------------
i.s.s.b.g.c.GwMessageDecoderBenchmark-meter
             count = 1
         mean rate = 4.81 events/second
     1-minute rate = 0.00 events/second
     5-minute rate = 0.00 events/second
    15-minute rate = 0.00 events/second

-- Timers ----------------------------------------------------------------------
i.s.s.b.g.c.GwMessageDecoderBenchmark-timer
             count = 0
         mean rate = 0.00 calls/second
     1-minute rate = 0.00 calls/second
     5-minute rate = 0.00 calls/second
    15-minute rate = 0.00 calls/second
               min = 0.00 nanoseconds
               max = 0.00 nanoseconds
              mean = 0.00 nanoseconds
            stddev = 0.00 nanoseconds
            median = 0.00 nanoseconds
              75% <= 0.00 nanoseconds
              95% <= 0.00 nanoseconds
              98% <= 0.00 nanoseconds
              99% <= 0.00 nanoseconds
            99.9% <= 0.00 nanoseconds



Process finished with exit code 0
```

**Comment by artem-v** [comment]
This is done.
