### ISSUE TITLE
Failed test 'ScalecubeServiceDiscoveryTest.testSingleNodeGroupIsStillGroup'

### ISSUE THREAD

**Issue by segabriel** [scalecube/scalecube-services#599]
Subject is `ScalecubeServiceDiscoveryTest.testSingleNodeGroupIsStillGroup:222`

```
I 0610-1432:42,506 i.s.s.d.BaseTest ***** Test started  : ScalecubeServiceDiscoveryTest.testSingleNodeGroupIsStillGroup(TestInfo) ***** [main]
I 0610-1432:42,597 i.s.s.d.ServiceDiscovery Service endpoint 633279be-d309-4abe-8b9b-0ac4d1f54d67 is about to be added, since member 97937351ABF36D658297@127.0.1.1:32845 has joined the cluster [sc-cluster-37709-13]
I 0610-1432:42,598 i.s.s.d.ServiceGroupDiscovery Service group ServiceGroup{id='af3d0ce5', size=1} added to the cluster [sc-cluster-37709-13]
I 0610-1432:42,599 i.s.s.d.ServiceDiscovery Service endpoint d9720147-4db6-4021-b6fd-63ec7191eb15 is about to be added, since member 606D53EDCB3A0A885927@127.0.1.1:35506 has joined the cluster [sc-cluster-37709-13]
I 0610-1432:42,643 i.s.s.d.ServiceDiscovery Service endpoint 1f49b468-585d-4d0c-a274-637bc9aca0e7 is about to be added, since member BD0705403FC7000D483F@127.0.1.1:37709 has joined the cluster [sc-cluster-35506-14]
I 0610-1432:42,654 i.s.s.d.ServiceDiscovery Service endpoint 633279be-d309-4abe-8b9b-0ac4d1f54d67 is about to be added, since member 97937351ABF36D658297@127.0.1.1:32845 has joined the cluster [sc-cluster-35506-14]
I 0610-1432:42,655 i.s.s.d.ServiceGroupDiscovery Service group ServiceGroup{id='af3d0ce5', size=1} added to the cluster [sc-cluster-35506-14]
I 0610-1432:42,656 i.s.s.d.ServiceDiscovery Service endpoint 1f49b468-585d-4d0c-a274-637bc9aca0e7 is about to be added, since member BD0705403FC7000D483F@127.0.1.1:37709 has joined the cluster [sc-cluster-32845-15]
I 0610-1432:42,726 i.s.s.d.ServiceDiscovery Service endpoint d9720147-4db6-4021-b6fd-63ec7191eb15 is about to be added, since member 606D53EDCB3A0A885927@127.0.1.1:35506 has joined the cluster [sc-cluster-32845-15]
I 0610-1432:43,297 i.s.c.ClusterImpl Cluster member 5D13644F2891C799E9BD@127.0.1.1:33902 has been shut down [sc-cluster-33902-7]
I 0610-1432:44,234 i.s.c.ClusterImpl Cluster member 73DB0D502BEF8F689E8C@127.0.1.1:41202 has been shut down [sc-cluster-io-epoll-1]
I 0610-1432:47,536 i.s.s.d.BaseTest ***** Test finished : ScalecubeServiceDiscoveryTest.testSingleNodeGroupIsStillGroup(TestInfo) ***** [main]
```

**Comment by segabriel** [comment]
I have an assumption that there is a race condition here `io.scalecube.services.discovery.ScalecubeServiceDiscoveryTest.RecordingServiceDiscovery#create`: 

```
static RecordingServiceDiscovery create(Supplier<Mono<ServiceDiscovery>> supplier) {
      RecordingServiceDiscovery result = new RecordingServiceDiscovery();
      supplier
          .get()
          .doOnNext(result.instance::onNext)
          .subscribe(
              sd -> {
                sd.listenDiscovery()
                    .log("listenDiscovery", Level.FINE)
                    .subscribe(result.discoveryEvents);
                sd.start() //
                    .log("listenInstance", Level.FINE)
                    .subscribe();
              });
      return result;
    }
```

**Comment by artem-v** [comment]
Failed at https://api.travis-ci.org/v3/job/555956503/log.txt

**Comment by artem-v** [comment]
For example locally this is how it's passing: 

```
I 0708-2250:38,958 i.s.s.d.BaseTest ***** Test started  : ScalecubeServiceDiscoveryTest.repetition 1 of 1000 ***** [main]
I 0708-2250:39,664 i.s.s.d.ServiceDiscovery Service endpoint 883f488d-187c-4c93-a758-d2dca67458de is about to be added, since member A1BDF32E9DD66401F8B6@127.0.0.1:33524 has joined the cluster [sc-cluster-44061-1]
I 0708-2250:39,664 i.s.s.d.ServiceGroupDiscovery Service group ServiceGroup{id='30ea232a', size=1} added to the cluster [sc-cluster-44061-1]
I 0708-2250:39,666 i.s.s.d.ServiceDiscovery Service endpoint bcc655ca-248d-428c-835e-e7d390f5bd3b is about to be added, since member 2F2DE8CBDFA557BBD27F@127.0.0.1:45132 has joined the cluster [sc-cluster-44061-1]
I 0708-2250:39,673 i.s.s.d.ServiceDiscovery Service endpoint 3b0a60fb-2857-4674-a7e1-271438832226 is about to be added, since member 0764A15C4BA2B1DF3B1F@127.0.0.1:44061 has joined the cluster [sc-cluster-33524-3]
I 0708-2250:39,673 i.s.s.d.ServiceDiscovery Service endpoint 3b0a60fb-2857-4674-a7e1-271438832226 is about to be added, since member 0764A15C4BA2B1DF3B1F@127.0.0.1:44061 has joined the cluster [sc-cluster-45132-2]
I 0708-2250:39,675 i.s.s.d.ServiceDiscovery Service endpoint 883f488d-187c-4c93-a758-d2dca67458de is about to be added, since member A1BDF32E9DD66401F8B6@127.0.0.1:33524 has joined the cluster [sc-cluster-45132-2]
I 0708-2250:39,681 i.s.s.d.ServiceGroupDiscovery Service group ServiceGroup{id='30ea232a', size=1} added to the cluster [sc-cluster-45132-2]
I 0708-2250:39,682 i.s.c.ClusterImpl Cluster member A1BDF32E9DD66401F8B6@127.0.0.1:33524 is shutting down [main]
I 0708-2250:39,704 i.s.s.d.ServiceDiscovery Service endpoint bcc655ca-248d-428c-835e-e7d390f5bd3b is about to be added, since member 2F2DE8CBDFA557BBD27F@127.0.0.1:45132 has joined the cluster [sc-cluster-33524-3]
I 0708-2250:39,709 i.s.s.d.ServiceDiscovery Service endpoint 883f488d-187c-4c93-a758-d2dca67458de is about to be removed, since member A1BDF32E9DD66401F8B6@127.0.0.1:33524 have left the cluster [sc-cluster-45132-2]
I 0708-2250:39,709 i.s.s.d.ServiceDiscovery Service endpoint 883f488d-187c-4c93-a758-d2dca67458de is about to be removed, since member A1BDF32E9DD66401F8B6@127.0.0.1:33524 have left the cluster [sc-cluster-44061-1]
I 0708-2250:39,709 i.s.s.d.ServiceGroupDiscovery Service group ServiceGroup{id='30ea232a', size=1} removed from the cluster [sc-cluster-44061-1]
I 0708-2250:39,709 i.s.s.d.ServiceGroupDiscovery Service group ServiceGroup{id='30ea232a', size=1} removed from the cluster [sc-cluster-45132-2]
I 0708-2250:40,212 i.s.s.d.BaseTest ***** Test finished : ScalecubeServiceDiscoveryTest.repetition 1 of 1000 ***** [main]
```

**Comment by artem-v** [comment]
And this log of how it's failing locally: 

```
I 0708-2250:40,219 i.s.s.d.BaseTest ***** Test started  : ScalecubeServiceDiscoveryTest.repetition 2 of 1000 ***** [main]
I 0708-2250:40,241 i.s.s.d.ServiceDiscovery Service endpoint 59175e16-865d-49e7-b262-af024d57f256 is about to be added, since member 3ADBBB137EBFE81C8A56@127.0.0.1:33058 has joined the cluster [sc-cluster-42251-4]
I 0708-2250:40,242 i.s.s.d.ServiceGroupDiscovery Service group ServiceGroup{id='c52e922b', size=1} added to the cluster [sc-cluster-42251-4]
I 0708-2250:40,250 i.s.s.d.ServiceDiscovery Service endpoint ef1b5db7-8558-4b70-bc37-378a07fe2ad8 is about to be added, since member 8BB0ACD50B5722003BF0@127.0.0.1:42945 has joined the cluster [sc-cluster-42251-4]
I 0708-2250:40,255 i.s.s.d.ServiceDiscovery Service endpoint 75e406ff-d53f-4272-9bb1-d2c32f922f57 is about to be added, since member 17BB87B186FAA973C93C@127.0.0.1:42251 has joined the cluster [sc-cluster-42945-5]
I 0708-2250:40,261 i.s.s.d.ServiceDiscovery Service endpoint 75e406ff-d53f-4272-9bb1-d2c32f922f57 is about to be added, since member 17BB87B186FAA973C93C@127.0.0.1:42251 has joined the cluster [sc-cluster-33058-6]
I 0708-2250:40,263 i.s.s.d.ServiceDiscovery Service endpoint 59175e16-865d-49e7-b262-af024d57f256 is about to be added, since member 3ADBBB137EBFE81C8A56@127.0.0.1:33058 has joined the cluster [sc-cluster-42945-5]
I 0708-2250:40,266 i.s.s.d.ServiceGroupDiscovery Service group ServiceGroup{id='c52e922b', size=1} added to the cluster [sc-cluster-42945-5]
I 0708-2250:40,426 i.s.s.d.ServiceDiscovery Service endpoint ef1b5db7-8558-4b70-bc37-378a07fe2ad8 is about to be added, since member 8BB0ACD50B5722003BF0@127.0.0.1:42945 has joined the cluster [sc-cluster-33058-6]
I 0708-2250:42,715 i.s.c.ClusterImpl Cluster member A1BDF32E9DD66401F8B6@127.0.0.1:33524 has been shut down [sc-cluster-33524-3]
I 0708-2250:45,227 i.s.s.d.BaseTest ***** Test finished : ScalecubeServiceDiscoveryTest.repetition 2 of 1000 ***** [main]

java.lang.AssertionError: VerifySubscriber timed out on reactor.core.publisher.FluxFlatMap$FlatMapMain@545b995e

	at reactor.test.ErrorFormatter.assertionError(ErrorFormatter.java:105)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.pollTaskEventOrComplete(DefaultStepVerifierBuilder.java:1603)
	at reactor.test.DefaultStepVerifierBuilder$DefaultVerifySubscriber.verify(DefaultStepVerifierBuilder.java:1190)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:802)
	at reactor.test.DefaultStepVerifierBuilder$DefaultStepVerifier.verify(DefaultStepVerifierBuilder.java:772)
	at io.scalecube.services.discovery.ScalecubeServiceDiscoveryTest.testSingleNodeGroupIsStillGroup(ScalecubeServiceDiscoveryTest.java:223)

```

**Comment by artem-v** [comment]
Fixed at https://github.com/scalecube/scalecube-services/pull/629
