### ISSUE TITLE
Fix annoying 'Operator called default onErrorDropped'

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#691]
Fix annoying exception: 

```
E 1106-1558:29,391 r.c.p.Operators Operator called default onErrorDropped [sc-cluster-io-epoll-1]
io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /127.0.0.1:4002
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source) ~[netty-transport-native-unix-common-4.1.36.Final.jar:4.1.36.Final]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:183)
	reactor.netty.resources.NewConnectionProvider.acquire(NewConnectionProvider.java:53)
Error has been observed by the following operator(s):
	|_	Mono.create â‡¢ reactor.netty.resources.NewConnectionProvider.acquire(NewConnectionProvider.java:53)
	|_	Mono.doOnError â‡¢ io.scalecube.transport.netty.TransportImpl.connect0(TransportImpl.java:330)
	|_	Mono.cache â‡¢ io.scalecube.transport.netty.TransportImpl.connect0(TransportImpl.java:335)
	|_	Mono.create â‡¢ io.scalecube.transport.netty.TransportImpl.getOrConnect(TransportImpl.java:314)
	|_	Mono.flatMap â‡¢ io.scalecube.transport.netty.TransportImpl.send(TransportImpl.java:242)
	|_	Mono.then â‡¢ io.scalecube.transport.netty.TransportImpl.send(TransportImpl.java:242)

Caused by: io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused
	... 1 more
W 1106-1558:29,423 i.n.u.c.DefaultPromise An exception was thrown by reactor.netty.resources.NewConnectionProvider$DisposableConnect.operationComplete() [sc-cluster-io-epoll-1]
reactor.core.Exceptions$BubblingException: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /127.0.0.1:4002
	at reactor.core.Exceptions.bubble(Exceptions.java:154) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.Operators.onErrorDropped(Operators.java:520) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.LambdaMonoSubscriber.onError(LambdaMonoSubscriber.java:113) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onError(MonoIgnoreElements.java:76) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onError(MonoFlatMap.java:165) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:180) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.LambdaMonoSubscriber.doError(LambdaMonoSubscriber.java:121) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.LambdaMonoSubscriber.onError(LambdaMonoSubscriber.java:116) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoProcessor$NextInner.onError(MonoProcessor.java:601) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoProcessor.onError(MonoProcessor.java:354) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxPeekFuseable$PeekFuseableSubscriber.onError(FluxPeekFuseable.java:228) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.FluxOnAssembly$OnAssemblySubscriber.onError(FluxOnAssembly.java:350) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.core.publisher.MonoCreate$DefaultMonoSink.error(MonoCreate.java:180) ~[reactor-core-3.2.9.RELEASE.jar:3.2.9.RELEASE]
	at reactor.netty.resources.NewConnectionProvider$DisposableConnect.operationComplete(NewConnectionProvider.java:160) ~[reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at reactor.netty.resources.NewConnectionProvider$DisposableConnect.operationComplete(NewConnectionProvider.java:106) ~[reactor-netty-0.8.8.RELEASE.jar:0.8.8.RELEASE]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:502) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:495) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:474) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:415) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:540) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.DefaultPromise.setFailure0(DefaultPromise.java:533) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.concurrent.DefaultPromise.tryFailure(DefaultPromise.java:114) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.fulfillConnectPromise(AbstractEpollChannel.java:634) [netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar:4.1.36.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:653) [netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar:4.1.36.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:527) [netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar:4.1.36.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:422) [netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar:4.1.36.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:333) [netty-transport-native-epoll-4.1.36.Final-linux-x86_64.jar:4.1.36.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:906) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.36.Final.jar:4.1.36.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_222]
Caused by: io.netty.channel.AbstractChannel$AnnotatedConnectException: syscall:getsockopt(..) failed: Connection refused: /127.0.0.1:4002
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source) ~[netty-transport-native-unix-common-4.1.36.Final.jar:4.1.36.Final]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Assembly trace from producer [reactor.core.publisher.MonoCreate] :
	reactor.core.publisher.Mono.create(Mono.java:183)
	reactor.netty.resources.NewConnectionProvider.acquire(NewConnectionProvider.java:53)
Error has been observed by the following operator(s):
	|_	Mono.create â‡¢ reactor.netty.resources.NewConnectionProvider.acquire(NewConnectionProvider.java:53)
	|_	Mono.doOnError â‡¢ io.scalecube.transport.netty.TransportImpl.connect0(TransportImpl.java:330)
	|_	Mono.cache â‡¢ io.scalecube.transport.netty.TransportImpl.connect0(TransportImpl.java:335)
	|_	Mono.create â‡¢ io.scalecube.transport.netty.TransportImpl.getOrConnect(TransportImpl.java:314)
	|_	Mono.flatMap â‡¢ io.scalecube.transport.netty.TransportImpl.send(TransportImpl.java:242)
	|_	Mono.then â‡¢ io.scalecube.transport.netty.TransportImpl.send(TransportImpl.java:242)

Caused by: io.netty.channel.unix.Errors$NativeConnectException: syscall:getsockopt(..) failed: Connection refused
	at io.netty.channel.unix.Socket.finishConnect(..)(Unknown Source) ~[netty-transport-native-unix-common-4.1.36.Final.jar:4.1.36.Final]
```

**Comment by artem-v** [comment]
From scalecube-services's travis job:  [log.txt](https://github.com/scalecube/scalecube-cluster/files/3815669/log.txt)

**Comment by artem-v** [comment]
This issue duplicates issue from scalecube-cluster https://github.com/scalecube/scalecube-cluster/issues/280   in order to check it on all levels.

**Comment by artem-v** [comment]
Not seeing this anymore. Closing.
