### ISSUE TITLE
Investigate exception during test run RSocketServiceTransportTest

### ISSUE THREAD

**Issue by artem-v** [scalecube/scalecube-services#697]
### Test:
`RSocketServiceTransportTest.test_remote_node_died_mono_never()`

### Exception in logs: 
```
I 0117-1248:36,129 i.s.s.BaseTest ***** Test started  : RSocketServiceTransportTest.test_remote_node_died_mono_never() ***** [main]
I 0117-1248:36,130 i.s.s.Microservices Starting Microservices@75648615ecff4ed4 [main]
I 0117-1248:36,149 i.s.s.Microservices Starting Microservices@646a83bf23e64425 [main]
I 0117-1248:36,188 i.s.s.t.r.RSocketServerTransport Accepted connection on [id: 0x84f1e579, L:/127.0.1.1:37955 - R:/127.0.0.1:55944] [rsocket-worker-8-1]
I 0117-1248:36,189 i.s.s.t.r.RSocketClientTransport Connected successfully on 127.0.1.1:37955 [rsocket-worker-7-1]
I 0117-1248:36,191 i.s.s.t.r.RSocketServiceAcceptor Accepted rSocket: io.rsocket.util.MultiSubscriberRSocket@774bdb6f, connectionSetup: io.rsocket.ConnectionSetupPayload$DefaultConnectionSetupPayload@5bfd0649 [rsocket-worker-8-1]
I 0117-1248:39,193 i.s.s.Microservices Shutting down Microservices@646a83bf23e64425 [main]
I 0117-1248:39,194 i.s.c.Cluster Cluster member e6b2f1505894697@127.0.1.1:37095 is shutting down [main]
I 0117-1248:40,784 i.s.c.Cluster Cluster member e6b2f1505894697@127.0.1.1:37095 has been shut down [sc-cluster-37095-12]
I 0117-1248:41,403 i.s.s.t.r.RSocketServerTransport Connection closed on [id: 0x84f1e579, L:/127.0.1.1:37955 ! R:/127.0.0.1:55944] [rsocket-worker-8-1]
E 0117-1248:41,435 r.c.p.Operators Operator called default onErrorDropped [rsocket-worker-7-1]
java.nio.channels.ClosedChannelException: null
	at io.rsocket.RSocketRequester.terminate(RSocketRequester.java:476) ~[rsocket-core-1.0.0-RC5.jar:?]
	at io.rsocket.RSocketRequester.lambda$new$0(RSocketRequester.java:94) ~[rsocket-core-1.0.0-RC5.jar:?]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.runFinally(FluxDoFinally.java:156) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at reactor.core.publisher.FluxDoFinally$DoFinallySubscriber.onComplete(FluxDoFinally.java:139) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at reactor.core.publisher.MonoProcessor$NextInner.onComplete(MonoProcessor.java:518) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at reactor.core.publisher.MonoProcessor.onNext(MonoProcessor.java:308) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at reactor.core.publisher.MonoProcessor.onComplete(MonoProcessor.java:265) ~[reactor-core-3.3.0.RELEASE.jar:3.3.0.RELEASE]
	at io.rsocket.internal.BaseDuplexConnection.dispose(BaseDuplexConnection.java:23) ~[rsocket-core-1.0.0-RC5.jar:?]
	at io.rsocket.transport.netty.TcpDuplexConnection.lambda$new$0(TcpDuplexConnection.java:61) ~[rsocket-transport-netty-1.0.0-RC5.jar:?]
	at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:500) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:493) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:472) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:413) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:538) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:527) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:98) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84) [netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1156) [netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:758) [netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:734) [netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:605) [netty-transport-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.shutdownInput(AbstractEpollChannel.java:479) [netty-transport-native-epoll-4.1.37.Final-linux-x86_64.jar:4.1.37.Final]
	at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:815) [netty-transport-native-epoll-4.1.37.Final-linux-x86_64.jar:4.1.37.Final]
	at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:424) [netty-transport-native-epoll-4.1.37.Final-linux-x86_64.jar:4.1.37.Final]
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:326) [netty-transport-native-epoll-4.1.37.Final-linux-x86_64.jar:4.1.37.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-common-4.1.37.Final.jar:4.1.37.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_232]
W 0117-1248:41,447 i.s.s.t.r.RSocketClientTransport Exception occurred at rsocket client transport: reactor.core.Exceptions$BubblingException: java.nio.channels.ClosedChannelException [rsocket-worker-7-1]
I 0117-1248:41,449 i.s.s.t.r.RSocketClientTransport Connection closed on 127.0.1.1:37955 [rsocket-worker-7-1]
I 0117-1248:43,605 i.s.s.Microservices Microservices@646a83bf23e64425 has been shut down [globalEventExecutor-2-15]
I 0117-1248:49,473 i.s.s.Microservices Shutting down Microservices@75648615ecff4ed4 [main]
I 0117-1248:49,475 i.s.c.Cluster Cluster member 22f6bb4e2e47f7@127.0.1.1:39929 is shutting down [main]
I 0117-1248:50,351 i.s.c.Cluster Cluster member 22f6bb4e2e47f7@127.0.1.1:39929 has been shut down [sc-cluster-io-epoll-1]
I 0117-1248:53,892 i.s.s.BaseTest ***** Test finished : RSocketServiceTransportTest.test_remote_node_died_mono_never() ***** [main]
I 0117-1248:53,892 i.s.s.Microservices Microservices@75648615ecff4ed4 has been shut down [globalEventExecutor-2-18]
```

**Comment by artem-v** [comment]
Not seeing this anymore. Closing.
